<?php

namespace Database\Seeders;

use App\Http\Modules\Countries\Models\Country;
use App\Http\Modules\Cities\Models\City;
use App\Http\Modules\Brands\Models\Brand;
use App\Http\Modules\Models\Models\Model;
use App\Http\Modules\CarFeatures\Models\CarFeature;
use Illuminate\Database\Seeder;

class InitialDataSeeder extends Seeder
{
    public function run(): void
    {
        // 1. Countries
        $egypt = Country::updateOrCreate(
            ['id' => 1],
            ['name' => ['ar' => 'مصر', 'en' => 'Egypt']]
        );

        // 2. Cities
        $cities = [
            ['ar' => 'القاهرة', 'en' => 'Cairo'],
            ['ar' => 'الجيزة', 'en' => 'Giza'],
            ['ar' => 'الإسكندرية', 'en' => 'Alexandria'],
            ['ar' => 'المنصورة', 'en' => 'Mansoura'],
            ['ar' => 'طنطا', 'en' => 'Tanta'],
            ['ar' => 'الزقازيق', 'en' => 'Zagazig'],
            ['ar' => 'بنها', 'en' => 'Banha'],
            ['ar' => 'دمنهور', 'en' => 'Damanhour'],
            ['ar' => 'شبين الكوم', 'en' => 'Shibin El Kom'],
            ['ar' => 'أسيوط', 'en' => 'Assiut'],
            ['ar' => 'سوهاج', 'en' => 'Sohag'],
            ['ar' => 'المنيا', 'en' => 'Minya'],
            ['ar' => 'قنا', 'en' => 'Qena'],
            ['ar' => 'الأقصر', 'en' => 'Luxor'],
            ['ar' => 'أسوان', 'en' => 'Aswan'],
            ['ar' => 'السويس', 'en' => 'Suez'],
            ['ar' => 'الإسماعيلية', 'en' => 'Ismailia'],
            ['ar' => 'بور سعيد', 'en' => 'Port Said'],
            ['ar' => 'الغردقة', 'en' => 'Hurghada'],
            ['ar' => 'شرم الشيخ', 'en' => 'Sharm El Sheikh'],
            ['ar' => 'مرسى مطروح', 'en' => 'Marsa Matrouh'],
            ['ar' => 'الفيوم', 'en' => 'Fayoum'],
            ['ar' => 'بني سويف', 'en' => 'Beni Suef'],
            ['ar' => 'كفر الشيخ', 'en' => 'Kafr El Sheikh'],
            ['ar' => 'دمياط', 'en' => 'Damietta'],
        ];

        foreach ($cities as $cityData) {
            City::updateOrCreate(
                ['name->en' => $cityData['en']],
                ['name' => $cityData, 'country_id' => $egypt->id]
            );
        }

        // 3. Car Brands & Models (Comprehensive List)
        $carBrands = [
            "Acura" => ["ILX", "TLX", "RLX", "RDX", "MDX", "NSX", "ZDX", "Integra Type R"],
            "Alfa Romeo" => ["Giulia", "Stelvio", "4C", "8C", "Spider", "GTV", "Giulia Quadrifoglio"],
            "Aston Martin" => ["DB11", "Vantage", "DBX", "DB9", "Rapide", "Valkyrie", "Vanquish"],
            "Audi" => ["A3", "A4", "A6", "Q3", "Q5", "Q7", "A5", "A8", "Q8", "R8", "TT", "RS6", "RS7"],
            "Bentley" => ["Continental", "Flying Spur", "Bentayga", "Mulsanne", "Arnage", "Azure", "Continental GT"],
            "BMW" => ["3 Series", "5 Series", "7 Series", "X1", "X3", "X5", "X6", "X7", "i3", "i8", "Z4", "M3", "M4", "M5"],
            "Buick" => ["Enclave", "Encore", "Envision", "LaCrosse", "Regal", "Verano", "Grand National"],
            "Cadillac" => ["ATS", "CTS", "XT5", "Escalade", "XT4", "XT6", "XTS", "SRX", "CTS-V"],
            "Chevrolet" => ["Spark", "Malibu", "Impala", "Equinox", "Tahoe", "Silverado", "Camaro", "Corvette", "Traverse", "Suburban", "Trailblazer", "SS", "Optra", "Aveo", "Lanos"],
            "Chrysler" => ["200", "300", "Pacifica", "Aspen", "Voyager", "Sebring", "PT Cruiser", "300 SRT"],
            "Citroen" => ["C3", "C4", "C5 Aircross", "C1", "C5", "C6", "DS4", "C4 VTS", "C-Elysee"],
            "Dodge" => ["Challenger", "Charger", "Durango", "Journey", "Grand Caravan", "Ram", "Viper", "Dart", "Avenger", "Magnum", "Hellcat"],
            "DS Automobiles" => ["DS 3", "DS 7", "DS 9", "DS 4", "DS 5", "DS 3 Performance"],
            "Ferrari" => ["488", "F8", "Portofino", "Roma", "812", "SF90", "GTC4Lusso", "LaFerrari", "Monza"],
            "Fiat" => ["500", "500X", "Panda", "Tipo", "124 Spider", "Bravo", "Punto", "Abarth 595", "128", "Shahin"],
            "Ford" => ["Fiesta", "Focus", "Mustang", "Explorer", "F-150", "Ranger", "Fusion", "Escape", "Edge", "Expedition", "Bronco", "Maverick", "EcoSport", "GT"],
            "Genesis" => ["G70", "G80", "G90", "GV70", "GV80", "Essentia"],
            "GMC" => ["Acadia", "Terrain", "Yukon", "Sierra", "Canyon", "Savanna", "Syclone"],
            "Honda" => ["Civic", "Accord", "Fit", "CR-V", "Pilot", "Ridgeline", "HR-V", "Odyssey", "Passport", "Civic Type R", "NSX"],
            "Hummer" => ["H1", "H2", "H3", "EV"],
            "Hyundai" => ["Elantra", "Sonata", "Tucson", "Santa Fe", "Palisade", "Veloster", "Kona", "Ioniq", "Venue", "Veloster N", "Accent", "Verna", "I10", "Bayon", "Creta"],
            "Infiniti" => ["Q50", "Q60", "Q70", "QX50", "QX60", "QX80", "Q30", "QX30", "Q60 Red Sport 400"],
            "Isuzu" => ["D-Max", "MU-X", "Trooper", "Rodeo"],
            "Jaguar" => ["XE", "XF", "XJ", "F-Pace", "E-Pace", "I-Pace", "F-Type", "XK"],
            "Jeep" => ["Wrangler", "Cherokee", "Grand Cherokee", "Compass", "Renegade", "Gladiator", "Patriot", "Commander", "Liberty", "Grand Cherokee SRT"],
            "Kia" => ["Rio", "Optima", "Sportage", "Sorento", "Telluride", "Stinger", "Forte", "Soul", "Seltos", "K5", "Carnival", "Cerato", "Picanto", "Xceed"],
            "Lamborghini" => ["Huracan", "Aventador", "Urus", "Gallardo", "Murcielago", "Diablo", "Countach"],
            "Lancia" => ["Ypsilon", "Delta", "Thema", "Stratos"],
            "Land Rover" => ["Range Rover", "Range Rover Sport", "Discovery", "Defender", "Range Rover Velar", "Range Rover Evoque", "SVR"],
            "Lexus" => ["IS", "ES", "GS", "RX", "NX", "LX", "UX", "GX", "RC", "LS", "LFA"],
            "Lincoln" => ["MKC", "MKZ", "Navigator", "Corsair", "Aviator", "Continental", "MKX", "MKT"],
            "Maserati" => ["Ghibli", "Levante", "Quattroporte", "GranTurismo", "GranCabrio", "MC20"],
            "Mazda" => ["Mazda3", "Mazda6", "CX-3", "CX-5", "CX-9", "MX-5", "CX-30", "RX-7", "RX-8"],
            "Mercedes" => ["A-Class", "C-Class", "E-Class", "S-Class", "GLA", "GLE", "GLC", "CLS", "G-Class", "SL-Class", "GLS", "AMG GT", "AMG C63"],
            "Mini" => ["Cooper", "Countryman", "Clubman", "Paceman", "John Cooper Works"],
            "Mitsubishi" => ["Mirage", "Lancer", "Outlander", "Pajero", "Eclipse Cross", "ASX", "L200", "Lancer Evolution", "Xpander"],
            "Nissan" => ["Altima", "Sentra", "Maxima", "Rogue", "Murano", "Pathfinder", "370Z", "GT-R", "Juke", "Kicks", "Versa", "Nismo", "Sunny", "Qashqai"],
            "Peugeot" => ["208", "308", "508", "2008", "3008", "5008", "207", "307", "407", "RCZ", "301"],
            "Porsche" => ["911", "Cayenne", "Macan", "Panamera", "Taycan", "718 Boxster", "718 Cayman"],
            "Renault" => ["Clio", "Megane", "Kadjar", "Koleos", "Talisman", "Captur", "Duster", "Megane RS", "Logan", "Sandero", "Stepway"],
            "Rolls-Royce" => ["Ghost", "Wraith", "Dawn", "Phantom", "Cullinan", "Silver Shadow", "Silver Spur"],
            "Saab" => ["9-3", "9-5", "9-4X", "900"],
            "Scion" => ["tC", "FR-S", "iQ", "xB", "xD"],
            "Seat" => ["Ibiza", "Leon", "Ateca", "Arona", "Tarraco", "Cupra"],
            "Skoda" => ["Octavia", "Superb", "Kodiaq", "Kamiq", "Karoq", "Scala", "RS", "Fabia"],
            "Smart" => ["Fortwo", "Forfour", "Roadster"],
            "SsangYong" => ["Tivoli", "Korando", "Rexton", "Musso", "Actyon"],
            "Subaru" => ["Impreza", "Legacy", "Outback", "Forester", "Crosstrek", "Ascent", "BRZ", "WRX", "STI", "XV"],
            "Suzuki" => ["Swift", "Vitara", "Jimny", "Celerio", "Baleno", "Ignis", "S-Cross", "Swift Sport", "Dzire", "Ertiga", "Ciaz"],
            "Tata" => ["Tiago", "Nexon", "Harrier", "Safari", "Hexa", "Altroz"],
            "Tesla" => ["Model S", "Model 3", "Model X", "Model Y", "Roadster", "Cybertruck"],
            "Toyota" => ["Corolla", "Camry", "Prius", "Yaris", "Highlander", "Land Cruiser", "Supra", "4Runner", "RAV4", "Tacoma", "Tundra", "C-HR", "86", "GR Yaris", "Fortuner", "Hilux", "Belta", "Rumion"],
            "Volkswagen" => ["Golf", "Passat", "Jetta", "Tiguan", "Atlas", "Arteon", "Beetle", "Touareg", "Polo", "ID.4", "Golf GTI", "Golf R"],
            "Volvo" => ["S60", "S90", "V60", "XC40", "XC60", "XC90", "V90", "S40", "Polestar 1", "Polestar 2"],
            "BYD" => ["F3", "Song", "Qin", "Han", "Tang", "Atto 3"],
            "Jetour" => ["X70", "X70 Plus", "X90 Plus", "Dashing"],
            "Changan" => ["Alsvin", "Eado", "CS15", "CS35 Plus", "CS55 Plus", "CS75 Plus", "Uni-K", "Uni-T"],
            "Haval" => ["Jolion", "H6", "Dargo"],
            "MG" => ["MG 5", "MG 6", "ZS", "RX5", "HS", "MG 4"],
            "Jac" => ["JS3", "JS4", "J7", "S3", "S4"],
            "GAC" => ["GS3", "GS4", "GA4", "Emkoo", "Empow"],
            "Chery" => ["Tiggo 3", "Tiggo 7", "Tiggo 8", "Arrizo 5", "Envy"],
            "Baic" => ["X3", "X5", "X7"],
            "Exeed" => ["LX", "TXL", "VX"],
            "Hongqi" => ["H5", "HS5", "E-HS9"],
            "Bestune" => ["T33", "T77", "T99"],
            "Forthing" => ["T5 Evo"],
            "Soueast" => ["DX3", "DX5", "DX7"],
            "DFSK" => ["Glory 580", "Eagle Pro", "Glory 330"],
            "Lada" => ["Granta", "Niva"],
            "Brilliance" => ["V3", "V5", "V6", "V7"],
            "Bugatti" => ["Chiron", "Veyron", "Divo", "Centodieci", "La Voiture Noire"],
            "McLaren" => ["720S", "570S", "P1", "Senna", "GT", "600LT", "765LT", "Artura"],
            "Koenigsegg" => ["Jesko", "Regera", "Agera RS", "Gemera", "CCX", "CCXR"],
            "Pagani" => ["Huayra", "Zonda", "Huayra BC", "Huayra Roadster", "Imola"],
            "Rimac" => ["C_Two", "Concept One"],
            "Lotus" => ["Evora", "Elise", "Exige", "Emira", "Evija"],
            "Spyker" => ["C8", "C12", "D12"],
            "W Motors" => ["Fenyr SuperSport", "Lykan HyperSport"],
            "Noble" => ["M600", "M400", "M12"],
            "Zenvo" => ["TS1", "TSR", "ST1"],
            "Gumpert" => ["Apollo", "Tornante"],
            "Arrinera" => ["Hussarya", "Venocara"],
            "Drako" => ["GTE"],
            "Faraday Future" => ["FF91"],
            "Lucid Motors" => ["Air"],
            "Rivian" => ["R1T", "R1S"],
            "Bollinger" => ["B1", "B2"],
            "Czinger" => ["21C"],
            "De Tomaso" => ["P72", "Pantera"],
            "Hennessey" => ["Venom F5", "Venom GT"],
            "Italdesign" => ["Zerouno", "Davinci"],
            "Pininfarina" => ["Battista"],
            "Radical" => ["RXC", "SR3"],
            "SSC" => ["Tuatara", "Aero"],
            "Vencer" => ["Sarthe", "Dodge"],
            "Wiesmann" => ["GT", "MF5"],
        ];

        foreach ($carBrands as $brandName => $models) {
            $brand = Brand::updateOrCreate(
                ['name->en' => $brandName],
                ['name' => ['en' => $brandName, 'ar' => $brandName], 'type' => 'car']
            );

            foreach ($models as $modelName) {
                Model::updateOrCreate(
                    ['name->en' => $modelName, 'brand_id' => $brand->id],
                    ['name' => ['en' => $modelName, 'ar' => $modelName], 'type' => 'car']
                );
            }
        }

        // 4. Motorcycle Brands & Models
        $motorcycleBrands = [
            "Harley-Davidson" => ["Sportster", "Softail", "Touring", "Street", "LiveWire"],
            "Honda" => ["CBR", "CB", "CRF", "Gold Wing", "Rebel", "Hornet", "Steed", "Shadow"],
            "Yamaha" => ["YZF-R", "MT", "XT", "Ténéré", "YZ", "R1", "R6", "TMAX", "VMAX"],
            "Kawasaki" => ["Ninja", "Z", "Versys", "KLR", "H2", "Vulcan"],
            "Ducati" => ["Panigale", "Monster", "Multistrada", "Scrambler", "Diavel"],
            "BMW" => ["S1000RR", "R1250GS", "F900R", "K1600", "C400"],
            "Suzuki" => ["GSX-R", "V-Strom", "Hayabusa", "Boulevard", "DR-Z", "Gixxer"],
            "KTM" => ["Duke", "RC", "Adventure", "Super Duke", "EXC"],
            "Triumph" => ["Bonneville", "Tiger", "Speed Triple", "Street Triple", "Rocket"],
            "Aprilia" => ["RSV4", "Tuono", "RS", "Shiver", "Dorsoduro"],
            "Royal Enfield" => ["Classic", "Bullet", "Interceptor", "Himalayan", "Meteor"],
            "Indian" => ["Scout", "Chief", "Chieftain", "Roadmaster", "FTR"],
            "MV Agusta" => ["F4", "Brutale", "Dragster", "Turismo Veloce", "Superveloce"],
            "Moto Guzzi" => ["V7", "V9", "V85", "California", "Griso"],
            "Benelli" => ["TNT", "TRK", "Leoncino", "Imperiale", "BN", "VLM", "VLR", "Zenzero"],
            "Bajaj" => ["Pulsar", "Dominar", "Avenger", "CT", "Platina", "Boxer"],
            "Kymco" => ["AK", "Like", "Agility", "Xciting", "Downtown"],
            "Vespa" => ["Primavera", "GTS", "Sprint", "LX", "946"],
            "Piaggio" => ["Beverly", "Medley", "Liberty", "MP3", "X10"],
            "SYM" => ["Symphony", "Fiddle", "Joyride", "Orbit", "Jet", "Cruisym"],
            "Dayun" => ["Dayun 4", "Dayun 6", "Dayun 10", "Dayun 40", "Dayun 2B"],
            "Haujue" => ["KA 150", "HJ 150", "HJ 150-9"],
            "Keeway" => ["Superlight", "RKS", "RKV"],
            "TVS" => ["Apache RTR", "HLX 150", "King"],
            "Halawa" => ["Tiger", "Express", "Halawa 4"],
            "Zongshen" => ["ZS 150", "ZS 200"],
            "Haojin" => ["Haojin 150", "Haojin 200"],
            "Husqvarna" => ["Vitpilen", "Svartpilen", "701"],
            "Norton" => ["Commando", "V4", "Atlas"],
            "Zontes" => ["310X", "350T", "350X"],
        ];

        foreach ($motorcycleBrands as $brandName => $models) {
            $brand = Brand::updateOrCreate(
                ['name->en' => $brandName],
                ['name' => ['en' => $brandName, 'ar' => $brandName], 'type' => 'motorcycle']
            );

            foreach ($models as $modelName) {
                Model::updateOrCreate(
                    ['name->en' => $modelName, 'brand_id' => $brand->id],
                    ['name' => ['en' => $modelName, 'ar' => $modelName], 'type' => 'motorcycle']
                );
            }
        }

        // 5. Car/Bike Features
        $features = [
            // الأمان والسلامة
            ['ar' => 'مانع انغلاق الفرامل', 'en' => 'Anti-lock Braking System (ABS)'],
            ['ar' => 'توزيع إلكتروني للفرامل', 'en' => 'Electronic Brakeforce Distribution (EBD)'],
            ['ar' => 'الثبات الإلكتروني', 'en' => 'Electronic Stability Program (ESP / ESC)'],
            ['ar' => 'مانع الانزلاق', 'en' => 'Traction Control System (TCS)'],
            ['ar' => 'مساعد الفرامل', 'en' => 'Brake Assist (BA)'],
            ['ar' => 'فرامل طوارئ تلقائية', 'en' => 'Autonomous Emergency Braking (AEB)'],
            ['ar' => 'تحذير الاصطدام الأمامي', 'en' => 'Forward Collision Warning (FCW)'],
            ['ar' => 'مساعد تفادي الاصطدام', 'en' => 'Collision Avoidance Assist'],
            ['ar' => 'مراقبة النقطة العمياء', 'en' => 'Blind Spot Monitoring (BSM)'],
            ['ar' => 'المحافظة على المسار', 'en' => 'Lane Keep Assist (LKA)'],
            ['ar' => 'تحذير الخروج من الحارة', 'en' => 'Lane Departure Warning (LDW)'],
            ['ar' => 'مساعد التمركز في الحارة', 'en' => 'Lane Centering Assist'],
            ['ar' => 'مثبت سرعة متكيف', 'en' => 'Adaptive Cruise Control (ACC)'],
            ['ar' => 'التعرف على الإشارات', 'en' => 'Traffic Sign Recognition (TSR)'],
            ['ar' => 'تنبيه انتباه السائق', 'en' => 'Driver Attention Alert'],
            ['ar' => 'تنبيه حركة خلفية', 'en' => 'Rear Cross Traffic Alert (RCTA)'],
            ['ar' => 'مساعد الركن', 'en' => 'Park Assist'],
            ['ar' => 'مساعد الركن التلقائي', 'en' => 'Automatic Parking Assist'],
            ['ar' => 'ركن ذاتي', 'en' => 'Self Parking / Auto Park'],
            ['ar' => 'مساعد صعود المرتفعات', 'en' => 'Hill Start Assist (HSA)'],
            ['ar' => 'نزول المنحدرات', 'en' => 'Hill Descent Control (HDC)'],
            ['ar' => 'نظام مراقبة ضغط الإطارات', 'en' => 'Tire Pressure Monitoring System (TPMS)'],
            ['ar' => 'كاميرا خلفية', 'en' => 'Rear View Camera'],
            ['ar' => 'كاميرا 360 محيطية', 'en' => '360° Surround View Camera'],
            ['ar' => 'رؤية ليلية', 'en' => 'Night Vision'],
            ['ar' => 'كشف المشاة', 'en' => 'Pedestrian Detection'],
            ['ar' => 'كشف الدراجات', 'en' => 'Cyclist Detection'],
            ['ar' => 'وسائد هوائية', 'en' => 'Airbags'],
            ['ar' => 'وسائد هوائية أمامية', 'en' => 'Front Airbags'],
            ['ar' => 'وسائد جانبية', 'en' => 'Side Airbags'],
            ['ar' => 'وسائد ستائرية', 'en' => 'Curtain Airbags'],
            ['ar' => 'وسادة ركبة', 'en' => 'Knee Airbag'],
            ['ar' => 'وسادة هوائية وسطية', 'en' => 'Center Airbag'],
            ['ar' => 'ISOFIX', 'en' => 'ISOFIX'],

            // إضافات الأمان والسلامة الجديدة
            ['ar' => 'مساعد تغيير الحارة النشط', 'en' => 'Active Lane Change Assist'],
            ['ar' => 'مساعد التوجيه في حالات الطوارئ', 'en' => 'Emergency Steering Assist'],
            ['ar' => 'مساعد التوجيه التفادي لمنع الاصطدام', 'en' => 'Evasive Steering Assist'],
            ['ar' => 'تنبيه عند فتح الأبواب والخروج', 'en' => 'Exit Warning'],
            ['ar' => 'مساعد الخروج الآمن', 'en' => 'Safe Exit Assist'],
            ['ar' => 'تنبيه حركة المرور الأمامية المتقاطعة', 'en' => 'Front Cross Traffic Alert'],
            ['ar' => 'مساعد عبور التقاطعات والمنحنيات', 'en' => 'Junction Assist'],
            ['ar' => 'مساعد القيادة في الاختناقات المرورية', 'en' => 'Traffic Jam Assist'],
            ['ar' => 'مساعد القيادة على الطرق السريعة', 'en' => 'Highway Assist'],
            ['ar' => 'مثبت سرعة استباقي ذكي', 'en' => 'Predictive Cruise Control'],
            ['ar' => 'مساعد التحكم في المسافة الآمنة', 'en' => 'Distance Control Assist'],
            ['ar' => 'مساعد التوقف التلقائي في حالات الطوارئ', 'en' => 'Emergency Stop Assist'],
            ['ar' => 'مراقبة خروج الركاب للتأمين', 'en' => 'Occupant Exit Monitoring'],
            ['ar' => 'نظام كشف وجود الأطفال داخل السيارة', 'en' => 'Child Presence Detection'],
            ['ar' => 'مساعد ثبات المقطورة والجر', 'en' => 'Trailer Stability Assist'],
            ['ar' => 'مساعد التحكم في المقطورات', 'en' => 'Trailer Assist'],
            ['ar' => 'مساعد الرجوع للخلف بالمقطورة', 'en' => 'Trailer Reverse Assist'],
            ['ar' => 'حساسات ركن محيطية 360 درجة', 'en' => 'Surround Parking Sensors'],
            ['ar' => 'حساسات ركن أمامية', 'en' => 'Front Parking Sensors'],
            ['ar' => 'حساسات ركن خلفية', 'en' => 'Rear Parking Sensors'],
            ['ar' => 'عرض غطاء المحرك الشفاف لكشف الطريق', 'en' => 'Transparent Hood View'],
            ['ar' => 'كاميرا أسفل السيارة للطرق الوعرة', 'en' => 'Underbody Camera'],
            ['ar' => 'كاميرا مراقبة المقطورة الخلفية', 'en' => 'Trailer Camera'],

            // الراحة والتجهيزات
            ['ar' => 'دخول ذكي', 'en' => 'Keyless Entry'],
            ['ar' => 'تشغيل بدون مفتاح', 'en' => 'Keyless Start'],
            ['ar' => 'تشغيل بالبصمة', 'en' => 'Push Button Start'],
            ['ar' => 'تشغيل عن بعد', 'en' => 'Remote Start'],
            ['ar' => 'فتح وإغلاق عن بعد', 'en' => 'Remote Access'],
            ['ar' => 'فرامل يد إلكترونية', 'en' => 'Electronic Parking Brake (EPB)'],
            ['ar' => 'تثبيت فرامل تلقائي', 'en' => 'Auto Hold'],
            ['ar' => 'غلق تلقائي للأبواب', 'en' => 'Auto Door Lock'],
            ['ar' => 'فتح الشنطة كهرباء', 'en' => 'Power Tailgate'],
            ['ar' => 'فتح الشنطة بالقدم', 'en' => 'Hands-Free Tailgate'],
            ['ar' => 'شفط الأبواب', 'en' => 'Soft Close Doors'],
            ['ar' => 'أبواب كهربائية', 'en' => 'Power Doors'],
            ['ar' => 'أبواب جانبية كهربائية انزلاقية', 'en' => 'Power Sliding Doors'],
            ['ar' => 'مرايات كهرباء', 'en' => 'Power Folding Mirrors'],
            ['ar' => 'مرايات تسخين', 'en' => 'Heated Mirrors'],
            ['ar' => 'مرايات تعتيم تلقائي', 'en' => 'Auto Dimming Mirrors'],
            ['ar' => 'مرايات ذاكرة', 'en' => 'Memory Mirrors'],
            ['ar' => 'مقاعد كهربائية', 'en' => 'Power Seats'],
            ['ar' => 'ذاكرة المقاعد', 'en' => 'Memory Seats'],
            ['ar' => 'تدفئة المقاعد', 'en' => 'Heated Seats'],
            ['ar' => 'تبريد المقاعد', 'en' => 'Ventilated Seats'],
            ['ar' => 'مساج المقاعد', 'en' => 'Massage Seats'],
            ['ar' => 'دعم قطني', 'en' => 'Lumbar Support'],
            ['ar' => 'مقاعد رياضية', 'en' => 'Sport Seats'],
            ['ar' => 'مقاعد رياضية حاضنة', 'en' => 'Bucket Seats'],
            ['ar' => 'تسخين المقاعد الخلفية', 'en' => 'Rear Heated Seats'],
            ['ar' => 'تبريد المقاعد الخلفية', 'en' => 'Rear Ventilated Seats'],
            ['ar' => 'تدفئة الدركسيون', 'en' => 'Heated Steering Wheel'],
            ['ar' => 'عجلة قيادة كهربائية', 'en' => 'Power Steering Wheel'],
            ['ar' => 'عجلة قيادة بذاكرة', 'en' => 'Memory Steering Wheel'],
            ['ar' => 'نظام تعطير الهواء المحيط', 'en' => 'Ambient Air Package'],
            ['ar' => 'تبريد حامل الأكواب', 'en' => 'Cooled Cup Holders'],
            ['ar' => 'تبريد درج التابلوه', 'en' => 'Cooled Glove Box'],

            // إضافات الراحة والتجهيزات الجديدة
            ['ar' => 'فتح قفل السيارة التلقائي عند الاقتراب', 'en' => 'Auto Unlock on Approach'],
            ['ar' => 'قفل السيارة التلقائي عند الابتعاد', 'en' => 'Walk Away Auto Lock'],
            ['ar' => 'ميزة الدخول المريح وسهولة الركوب', 'en' => 'Comfort Access'],
            ['ar' => 'مساعد الدخول والخروج المريح', 'en' => 'Easy Entry / Exit'],
            ['ar' => 'وظيفة الترحيب بالمقعد وتحريكه للخلف', 'en' => 'Welcome Seat Function'],
            ['ar' => 'امتداد وسادة المقعد لدعم الفخذين', 'en' => 'Seat Extension'],
            ['ar' => 'جوانب مقاعد قابلة للتعديل والتحكم', 'en' => 'Adjustable Side Bolsters'],
            ['ar' => 'تعديل ديناميكي نشط للمقعد مع المنعطفات', 'en' => 'Dynamic Seat Adjustment'],
            ['ar' => 'إمالة المقاعد الخلفية كهربائياً', 'en' => 'Rear Seat Recline'],
            ['ar' => 'مقاعد صالة رجال الأعمال الفاخرة بالخلف', 'en' => 'Executive Lounge Seats'],
            ['ar' => 'مقاعد كابتن منفصلة بالصف الثاني', 'en' => 'Captain Seats'],
            ['ar' => 'مقاعد خلفية قابلة للطي', 'en' => 'Folding Rear Seats'],
            ['ar' => 'مقاعد قابلة للطي بنسبة 60/40', 'en' => 'Split Folding Seats'],
            ['ar' => 'تحكم كهربائي بالمقاعد الخلفية', 'en' => 'Power Rear Seats'],
            ['ar' => 'تبريد وتهوية المقاعد الخلفية', 'en' => 'Ventilated Rear Seats'],
            ['ar' => 'نظام مساج للمقاعد الخلفية', 'en' => 'Rear Massage Seats'],
            ['ar' => 'تهوية مقاعد نشطة متكيفة', 'en' => 'Active Seat Ventilation'],
            ['ar' => 'تدفئة الرقبة (أوشحة تدفئة هوائية)', 'en' => 'Neck Heater'],
            ['ar' => 'مساند ذراع مدفأة بالكامل', 'en' => 'Heated Armrests'],
            ['ar' => 'ألواح أبواب داخلية مدفأة', 'en' => 'Heated Door Panels'],
            ['ar' => 'حوامل أكواب بنظام تسخين', 'en' => 'Heated Cup Holders'],
            ['ar' => 'فتحات رشاشات مساحات مدفأة ضد التجمد', 'en' => 'Heated Washer Nozzles'],
            ['ar' => 'طي التلقائي للمرايا عند القفل', 'en' => 'Auto Folding Mirrors'],
            ['ar' => 'إمالة المرايا للأسفل عند الرجوع للخلف', 'en' => 'Reverse Tilt Mirror'],
            ['ar' => 'أبواب بدون إطار زجاجي', 'en' => 'Frameless Doors'],
            ['ar' => 'أبواب شفط مريحة', 'en' => 'Vacuum Doors'],

            // الشاشات والتكنولوجيا
            ['ar' => 'عدادات رقمية', 'en' => 'Digital Instrument Cluster'],
            ['ar' => 'العدادات الافتراضية الذكية', 'en' => 'Virtual Cockpit'],
            ['ar' => 'شاشة معلومات وترفيه', 'en' => 'Infotainment Display'],
            ['ar' => 'شاشة راكب', 'en' => 'Passenger Display'],
            ['ar' => 'شاشة خلفية', 'en' => 'Rear Entertainment Screens'],
            ['ar' => 'عرض على الزجاج', 'en' => 'Head-Up Display (HUD)'],
            ['ar' => 'عرض المعلومات بالواقع المعزز', 'en' => 'Augmented Reality Head-Up Display'],
            ['ar' => 'شاحن لاسلكي', 'en' => 'Wireless Charging'],
            ['ar' => 'أبل كاربلاي', 'en' => 'Apple CarPlay'],
            ['ar' => 'أندرويد أوتو', 'en' => 'Android Auto'],
            ['ar' => 'أبل كاربلاي لاسلكي', 'en' => 'Wireless Apple CarPlay'],
            ['ar' => 'أندرويد أوتو لاسلكي', 'en' => 'Wireless Android Auto'],
            ['ar' => 'أوامر صوتية', 'en' => 'Voice Control'],
            ['ar' => 'مساعد ذكي', 'en' => 'AI Assistant'],
            ['ar' => 'نظام ملاحة', 'en' => 'Navigation System (GPS)'],
            ['ar' => 'تحديثات عبر الإنترنت', 'en' => 'Over-the-Air Updates (OTA)'],
            ['ar' => 'واي فاي داخلي', 'en' => 'In-Car Wi-Fi'],
            ['ar' => 'نقاط USB-C', 'en' => 'USB-C Ports'],
            ['ar' => 'كاميرا تسجيل', 'en' => 'Dash Cam'],
            ['ar' => 'مفتاح رقمي', 'en' => 'Digital Key'],
            ['ar' => 'مفتاح الاتصال قريب المدى NFC', 'en' => 'NFC Key'],
            ['ar' => 'تكامل الهاتف الذكي', 'en' => 'Smartphone Integration'],
            ['ar' => 'الخدمات المتصلة', 'en' => 'Connected Services'],
            ['ar' => 'التحكم بالمركبة عن بعد', 'en' => 'Remote Vehicle Control'],
            ['ar' => 'التحكم بالإيماءات وحركات اليد', 'en' => 'Gesture Control'],
            ['ar' => 'مرآة خلفية رقمية بكاميرا', 'en' => 'Digital Rear View Mirror'],

            // إضافات الشاشات والتكنولوجيا الجديدة
            ['ar' => 'شاشة عرض منحنية فائقة الدقة', 'en' => 'Curved Display'],
            ['ar' => 'شاشات بتقنية OLED عالية التباين', 'en' => 'OLED Display'],
            ['ar' => 'شاشات عرض شفافة مبتكرة', 'en' => 'Transparent Display'],
            ['ar' => 'شاشة ترفيهية خاصة بالراكب الأمامي', 'en' => 'Passenger Entertainment Display'],
            ['ar' => 'نظام ترفيهي لركاب المقاعد الخلفية', 'en' => 'Rear Seat Entertainment'],
            ['ar' => 'دمج خدمات البث الترفيهي (نتفليكس، يوتيوب)', 'en' => 'Streaming Services Integration'],
            ['ar' => 'تطبيقات مدمجة بنظام السيارة الذكي', 'en' => 'Built-in Apps'],
            ['ar' => 'مزامنة ملفات المستخدم السحابية', 'en' => 'Cloud Profile Sync'],
            ['ar' => 'ملفات تعريف متعددة للمستخدمين بالذاكرة', 'en' => 'Multiple User Profiles'],
            ['ar' => 'نظام التعرف على ملامح الوجه للتشغيل والأمان', 'en' => 'Face Recognition'],
            ['ar' => 'تحديد هوية السائق وضبط إعداداته تلقائياً', 'en' => 'Driver Identification'],
            ['ar' => 'نظام البصمة لتشغيل السيارة وحفظ الإعدادات', 'en' => 'Fingerprint Authentication'],
            ['ar' => 'نظام الدخول بالقياسات الحيوية (الوجه/البصمة)', 'en' => 'Biometric Access'],
            ['ar' => 'تكامل كامل وشامل بين الهاتف والسيارة', 'en' => 'Vehicle-to-Phone Integration'],
            ['ar' => 'تكامل السيارة مع المنزل الذكي', 'en' => 'Vehicle-to-Home Integration'],
            ['ar' => 'ميزة تزويد الأجهزة الخارجية بالطاقة V2L', 'en' => 'Vehicle-to-Load (V2L)'],
            ['ar' => 'اتصال المركبة بالمركبات الأخرى V2V', 'en' => 'Vehicle-to-Vehicle Communication (V2V)'],
            ['ar' => 'اتصال المركبة بالبنية التحتية للطرق V2I', 'en' => 'Vehicle-to-Infrastructure (V2I)'],
            ['ar' => 'شريحة اتصال إلكترونية مدمجة eSIM', 'en' => 'eSIM Connectivity'],
            ['ar' => 'اتصال مباشر بالأقمار الصناعية للطويرئ', 'en' => 'Satellite Connectivity'],
            ['ar' => 'كتيب دليل المالك الرقمي المدمج بالشاشة', 'en' => 'Digital Owner Manual'],
            ['ar' => 'مسجل بيانات الحوادث والأحداث (الصندوق الأسود)', 'en' => 'Event Data Recorder'],
            ['ar' => 'خدمات الملاحة وتحديثات المرور الحية', 'en' => 'Live Traffic Services'],
            ['ar' => 'نظام الركن الذكي والتحكم بالمفتاح عن بعد', 'en' => 'Remote Parking'],
            ['ar' => 'وضعية استدعاء السيارة عن بعد Summon', 'en' => 'Summon Mode'],
            ['ar' => 'الاستدعاء الذكي للسيارة من المواقف المزدحمة', 'en' => 'Smart Summon'],
            ['ar' => 'تشغيل مكيف السيارة وتدفئة المقاعد عن بعد', 'en' => 'Remote Climate Control'],
            ['ar' => 'تهيئة درجة حرارة الكابينة مسبقاً', 'en' => 'Cabin Preconditioning'],

            // الإضاءة
            ['ar' => 'مصابيح LED', 'en' => 'LED Headlights'],
            ['ar' => 'مصابيح Matrix', 'en' => 'Matrix LED Headlights'],
            ['ar' => 'مصابيح ليزر', 'en' => 'Laser Headlights'],
            ['ar' => 'إضاءة متكيفة', 'en' => 'Adaptive Headlights'],
            ['ar' => 'مساعد الضوء العالي المتكيف', 'en' => 'Adaptive High Beam Assist'],
            ['ar' => 'إضاءة عادية وعالية تلقائية', 'en' => 'Automatic High Beam'],
            ['ar' => 'إضاءة نهارية', 'en' => 'Daytime Running Lights (DRL)'],
            ['ar' => 'إشارات متحركة', 'en' => 'Dynamic Turn Signals'],
            ['ar' => 'إضاءة ترحيبية', 'en' => 'Welcome Lights'],
            ['ar' => 'إضاءة محيطية', 'en' => 'Ambient Lighting'],
            ['ar' => 'إضاءة داخلية متعددة الألوان', 'en' => 'Multi-Color Ambient Lighting'],
            ['ar' => 'إضاءة شعار', 'en' => 'Logo Projection Lights'],
            ['ar' => 'إضاءة المنعطفات', 'en' => 'Cornering Lights'],

            // إضافات الإضاءة الجديدة
            ['ar' => 'مصابيح بكسل ليد الرقمية الفائقة Pixel LED', 'en' => 'Pixel LED Headlights'],
            ['ar' => 'مصابيح خلفية بتقنية OLED ثلاثية الأبعاد', 'en' => 'OLED Tail Lights'],
            ['ar' => 'تقنية الإضاءة الرقمية فائقة الوضوح والبروجكتر', 'en' => 'Digital Light'],
            ['ar' => 'تأثيرات إضاءة متحركة وترحيبية', 'en' => 'Animated Lighting'],
            ['ar' => 'إشارات انعطاف تتابعية متحركة', 'en' => 'Sequential Indicators'],
            ['ar' => 'عرض متحرك ترحيبي بالأنوار الخارجية', 'en' => 'Welcome Animation'],
            ['ar' => 'عرض متحرك وداعي بالأنوار الخارجية', 'en' => 'Goodbye Animation'],
            ['ar' => 'أضواء فرامل طوارئ متكيفة سريعة الوميض', 'en' => 'Adaptive Brake Lights'],
            ['ar' => 'مساعد الإضاءة الديناميكي لمنع إبهار الآخرين', 'en' => 'Dynamic Light Assist'],
            ['ar' => 'إضاءة جانبية إضافية عند الانعطاف', 'en' => 'Corner Illumination'],
            ['ar' => 'إضاءة ترحيبية أسفل الأبواب وعلى الأرض', 'en' => 'Puddle Lamps'],

            // السقف والزجاج
            ['ar' => 'فتحة سقف', 'en' => 'Sunroof'],
            ['ar' => 'فتحة سقف بانوراما', 'en' => 'Panoramic Sunroof'],
            ['ar' => 'سقف زجاجي بانورامي ثابت', 'en' => 'Panoramic Glass Roof'],
            ['ar' => 'سقف زجاجي ثابت', 'en' => 'Fixed Glass Roof'],
            ['ar' => 'فتحة سقف كهربائية', 'en' => 'Power Sunroof'],
            ['ar' => 'سقف كهربائي قماشي', 'en' => 'Convertible Roof'],
            ['ar' => 'سقف إلكتروكرومي ذكي متغير التظليل', 'en' => 'Electrochromic Roof'],
            ['ar' => 'زجاج عازل', 'en' => 'Acoustic Glass'],
            ['ar' => 'زجاج مزدوج', 'en' => 'Double Glazed Glass'],
            ['ar' => 'زجاج خلفية مظلل', 'en' => 'Privacy Glass'],
            ['ar' => 'زجاج أمامي بنظام تدفئة لإزالة الصقيع', 'en' => 'Heated Windshield'],
            ['ar' => 'مساحات بمستشعر المطر تلقائية', 'en' => 'Rain Sensing Wipers'],

            // إضافات السقف والزجاج الجديدة
            ['ar' => 'طلاء خارجي ذكي معالج للخدوش البسيطة ذاتياً', 'en' => 'Self Healing Paint'],
            ['ar' => 'باقة الطلاء الخارجي المطفي المميز Matte Paint', 'en' => 'Matte Paint Package'],
            ['ar' => 'سقف السيارة الخارجي باللون الأسود اللامع', 'en' => 'Black Roof'],
            ['ar' => 'سقف سيارة رياضي مصنوع من ألياف الكربون', 'en' => 'Carbon Roof'],
            ['ar' => 'غطاء محرك نشط للحماية وامتصاص الصدمات', 'en' => 'Active Hood'],
            ['ar' => 'غطاء صندوق أمتعة أمامي كهربائي بالكامل', 'en' => 'Powered Frunk'],
            ['ar' => 'قفل وشفط صندوق الأمتعة الخلفي ناعم الملمس', 'en' => 'Soft Close Trunk'],
            ['ar' => 'صندوق أمتعة أمامي يفتح ويغلق كهربائياً Frunk', 'en' => 'Power Frunk'],
            ['ar' => 'زجاج أمامي بنظام عزل صوتي إضافي مضاعف', 'en' => 'Acoustic Windshield'],
            ['ar' => 'زجاج خلفي مدفأ لإزالة الصقيع وضباب الطريق', 'en' => 'Heated Rear Window'],
            ['ar' => 'زجاج عازل وواقٍ من الأشعة فوق البنفسجية', 'en' => 'UV Protection Glass'],
            ['ar' => 'زجاج تظليل ذكي يتغير أوتوماتيكياً', 'en' => 'Smart Tint Glass'],
            ['ar' => 'نوافذ إلكتروكرومية ذكية متغيرة التعتيم', 'en' => 'Electrochromic Windows'],

            // الأداء والقيادة
            ['ar' => 'أوضاع قيادة', 'en' => 'Drive Modes'],
            ['ar' => 'تعليق متكيف', 'en' => 'Adaptive Suspension'],
            ['ar' => 'تعليق هوائي', 'en' => 'Air Suspension'],
            ['ar' => 'نظام تعليق نشط', 'en' => 'Active Suspension'],
            ['ar' => 'توجيه خلفي', 'en' => 'Rear Wheel Steering'],
            ['ar' => 'نظام دفع رباعي', 'en' => 'All Wheel Drive (AWD)'],
            ['ar' => 'نظام دفع رباعي مستمر 4WD', 'en' => 'Four Wheel Drive (4WD)'],
            ['ar' => 'توجيه وتوزيع عزم الدوران', 'en' => 'Torque Vectoring'],
            ['ar' => 'لانش كنترول', 'en' => 'Launch Control'],
            ['ar' => 'قفل دفرنس', 'en' => 'Differential Lock'],
            ['ar' => 'ترس تفاضلي إلكتروني', 'en' => 'Electronic Differential'],
            ['ar' => 'ترس تفاضلي رياضي لزيادة الثبات', 'en' => 'Sport Differential'],
            ['ar' => 'عادم رياضي', 'en' => 'Sport Exhaust'],
            ['ar' => 'نظام إيقاف وتشغيل', 'en' => 'Start / Stop System'],
            ['ar' => 'محدد التروس الدوار / ناقل الحركة الذكي', 'en' => 'Drive Selector'],
            ['ar' => 'نظام الديناميكا الهوائية النشط', 'en' => 'Active Aerodynamics'],
            ['ar' => 'سبويلر خلفي نشط متحرك', 'en' => 'Active Spoiler'],
            ['ar' => 'قيادة شبه ذاتية', 'en' => 'Semi-Autonomous Driving'],
            ['ar' => 'قيادة ذاتية', 'en' => 'Autonomous Driving'],
            ['ar' => 'مسجل بيانات الأداء الرياضي', 'en' => 'Performance Data Recorder'],

            // إضافات الأداء والقيادة الجديدة
            ['ar' => 'قواعد محرك نشطة ديناميكية لتقليل الاهتزازات', 'en' => 'Active Engine Mounts'],
            ['ar' => 'نظام التحكم الديناميكي بالشاسيه والاتزان DCC', 'en' => 'Dynamic Chassis Control'],
            ['ar' => 'نظام تعليق استباقي يقرأ عيوب الطريق مسبقاً', 'en' => 'Predictive Suspension'],
            ['ar' => 'تحكم إلكتروني متكامل بالمساعدين وقوة الدعم EDC', 'en' => 'Electronic Damper Control'],
            ['ar' => 'نظام التعليق الهوائي المتطور متكيف الارتفاع ABC', 'en' => 'Air Body Control'],
            ['ar' => 'نظام منع تدحرج وجنوح الهيكل النشط بالمنعطفات', 'en' => 'Active Roll Stabilization'],
            ['ar' => 'ترس تفاضلي خلفي ذكي متطور', 'en' => 'Rear Differential'],
            ['ar' => 'وضعية الانجراف والتفحيط الرياضية المحكمة Drift Mode', 'en' => 'Drift Mode'],
            ['ar' => 'وضعية الحلبات والسباقات القصوى Race Mode', 'en' => 'Race Mode'],
            ['ar' => 'وضعية القيادة على الطرق الوعرة والرمال الصعبة', 'en' => 'Off-Road Mode'],
            ['ar' => 'وضعية القيادة الآمنة على الثلوج والجليد', 'en' => 'Snow Mode'],
            ['ar' => 'وضعية القيادة للرمال والصحاري الصعبة', 'en' => 'Sand Mode'],
            ['ar' => 'وضعية القيادة المخصصة بالكامل للسائق Individual', 'en' => 'Individual Mode'],
            ['ar' => 'وضعية المضمار والتسارع الرياضي الدقيق Track Mode', 'en' => 'Track Mode'],
            ['ar' => 'موزع عزم الدوران الذكي بين العجلات', 'en' => 'Torque Splitter'],
            ['ar' => 'مساعد التسارع الذكي والانطلاق Launch Assist', 'en' => 'Launch Assist'],
            ['ar' => 'القيادة بدواسة واحدة للتسارع والكبح التلقائي', 'en' => 'One Pedal Driving'],
            ['ar' => 'فرامل استعادة الطاقة وإعادة شحن البطارية', 'en' => 'Regenerative Braking'],
            ['ar' => 'استعادة طاقة الكبح لشحن بطاريات السيارة', 'en' => 'Brake Energy Recovery'],
            ['ar' => 'نظام رفع السيارة الهيدروليكي للمطبات والارتفاع', 'en' => 'Lift System'],
            ['ar' => 'نظام رفع المحور الأمامي لتفادي المطبات والصخور', 'en' => 'Front Axle Lift'],
            ['ar' => 'نظام رفع المحور الخلفي لتفادي الاحتكاك', 'en' => 'Rear Axle Lift'],
            ['ar' => 'صمامات عادم نشطة ذكية لتغيير نغمة الصوت الصوتية', 'en' => 'Active Exhaust Valves'],

            // التكييف والهواء
            ['ar' => 'تكييف ثنائي المناطق', 'en' => 'Dual Zone Climate Control'],
            ['ar' => 'تكييف ثلاثي المناطق مستقل', 'en' => 'Three Zone Climate Control'],
            ['ar' => 'أربع مناطق تكييف مستقلة', 'en' => 'Four Zone Climate Control'],
            ['ar' => 'تبريد خلفي مستقل', 'en' => 'Rear Climate Control'],
            ['ar' => 'تنقية الهواء', 'en' => 'Air Purification System'],
            ['ar' => 'معطر تكييف داخلي ذكي', 'en' => 'Fragrance System'],
            ['ar' => 'نظام تأيين وتنقية الهواء', 'en' => 'Ionizer'],

            // إضافات التكييف والهواء الجديدة
            ['ar' => 'فلتر هيبا فائق الجودة والتعقيم HEPA Filter', 'en' => 'HEPA Filter'],
            ['ar' => 'نظام العلاج العطري الطبيعي المدمج بالسيارة', 'en' => 'Aromatherapy System'],
            ['ar' => 'نظام تعطير الكابينة بروائح مخصصة فاخرة', 'en' => 'Cabin Scent System'],
            ['ar' => 'نظام المراقبة المستمرة لجودة ونقاء الهواء', 'en' => 'Air Quality Monitoring'],
            ['ar' => 'فلتر جزيئات هواء فائق الصغر والكفاءة PM2.5', 'en' => 'PM2.5 Filter'],
            ['ar' => 'نظام تعقيم الهواء بالأشعة فوق البنفسجية من البكتيريا', 'en' => 'UV Air Sterilization'],

            // الفخامة والداخلية
            ['ar' => 'نظام صوتي ممتاز', 'en' => 'Premium Sound System'],
            ['ar' => 'صوت ثلاثي الأبعاد', 'en' => '3D Surround Sound'],
            ['ar' => 'عزل الضوضاء النشط للهدوء', 'en' => 'Noise Cancellation'],
            ['ar' => 'جلد نابا', 'en' => 'Nappa Leather'],
            ['ar' => 'ألكانتارا', 'en' => 'Alcantara Interior'],
            ['ar' => 'تطعيم خشب', 'en' => 'Wood Trim'],
            ['ar' => 'تطعيم كربون', 'en' => 'Carbon Fiber Trim'],
            ['ar' => 'عتبات أبواب مضيئة بشعار السيارة', 'en' => 'Illuminated Door Sills'],
            ['ar' => 'ثلاجة', 'en' => 'Refrigerator'],
            ['ar' => 'مقاعد خلفية فاخرة لرجال الأعمال', 'en' => 'Executive Rear Seats'],
            ['ar' => 'مقاعد خلفية مريحة مع مسند أقدام Ottoman', 'en' => 'Rear Ottoman Seats'],
            ['ar' => 'سقف نجوم', 'en' => 'Starlight Headliner'],
            ['ar' => 'تابلت خلفي للتحكم بالأنظمة والترفيه', 'en' => 'Rear Tablet Controls'],
            ['ar' => 'الباقة التنفيذية الفاخرة للمقاعد الخلفية', 'en' => 'Rear Executive Package'],
            ['ar' => 'باقة الخصوصية والستائر الجانبية', 'en' => 'Privacy Package'],
            ['ar' => 'باقة السائق الخاصة بالفخامة', 'en' => 'Chauffeur Package'],

            // إضافات الفخامة والداخلية الجديدة
            ['ar' => 'نظام حجب وإلغاء الضوضاء الخارجية النشط', 'en' => 'Active Noise Cancellation'],
            ['ar' => 'باقة الراحة الصوتية والعزل الكامل المتطور', 'en' => 'Acoustic Comfort Package'],
            ['ar' => 'عزل صوتي مزدوج للأبواب والزجاج لراحة كاملة', 'en' => 'Double Insulation'],

            // الباقات
            ['ar' => 'باقة الفخامة', 'en' => 'Luxury Package'],
            ['ar' => 'الباقة الرياضية', 'en' => 'Sport Package'],
            ['ar' => 'باقة إس لاين الرياضية من أودي S-Line', 'en' => 'S Line Package'],
            ['ar' => 'باقة إم سبورت الرياضية من بي إم دبليو M Sport', 'en' => 'M Sport Package'],
            ['ar' => 'باقة إيه إم جي الرياضية من مرسيدس AMG', 'en' => 'AMG Package'],
            ['ar' => 'الباقة السوداء الرياضية الكاملة للسيارة Black Optics', 'en' => 'Black Optics Package'],
            ['ar' => 'باقة ألياف الكربون الخارجية والداخلية Carbon Fiber', 'en' => 'Carbon Package'],
            ['ar' => 'باقة الطرق الوعرة والرمال والارتفاع', 'en' => 'Off-Road Package'],
            ['ar' => 'باقة سحب المقطورات والجر', 'en' => 'Towing Package'],
            ['ar' => 'باقة الشتاء والتدفئة المتكاملة', 'en' => 'Winter Package'],
            ['ar' => 'باقة التكنولوجيا والأنظمة الذكية المتطورة', 'en' => 'Technology Package'],
            ['ar' => 'باقة مساعدة السائق والتحكم الذكي بالسرعة', 'en' => 'Driver Assistance Package'],
            ['ar' => 'الباقة المميزة الفاخرة Premium', 'en' => 'Premium Package'],
            ['ar' => 'باقة بريميوم بلس الإضافية Premium Plus', 'en' => 'Premium Plus Package'],
            ['ar' => 'الباقة الفاخرة القصوى بريستيج Prestige', 'en' => 'Prestige Package'],
            ['ar' => 'باقة الخيارات الكاملة الفول أوبشن Full Option', 'en' => 'Full Option Package'],

            // الباقات الجديدة
            ['ar' => 'الباقة التنفيذية الفاخرة للقيادة والركاب', 'en' => 'Executive Package'],
            ['ar' => 'باقة السائق الخاصة بالتحكم وتعديل المقاعد', 'en' => 'Chauffeur Package'],
            ['ar' => 'باقة الخصوصية والستائر الخلفية والجانبية المدمجة', 'en' => 'Rear Privacy Package'],
            ['ar' => 'باقة التدخين المتكاملة للمقاعد', 'en' => 'Smoking Package'],
            ['ar' => 'باقة غير المدخنين الخالية من طفايات السجائر', 'en' => 'Non-Smoking Package'],
            ['ar' => 'باقة الطاقس البارد والثلجي والتدفئة الشاملة', 'en' => 'Cold Weather Package'],
            ['ar' => 'باقة الطقس الحار والتبريد الإضافي للمحرك والركاب', 'en' => 'Hot Climate Package'],
            ['ar' => 'باقة القطر والجر للمقطورات والربط المتطور', 'en' => 'Tow Package'],
            ['ar' => 'باقة المغامرات والرحلات البرية الصعبة وتجهيزاتها', 'en' => 'Adventure Package'],
            ['ar' => 'باقة المظهر الخارجي الأنيق واللمسات الجمالية', 'en' => 'Appearance Package'],
            ['ar' => 'باقة كومبتيشن الرياضية والسرعة الفائقة', 'en' => 'Competition Package'],
            ['ar' => 'باقة إصدار التدشين المحدود والحصري للسيارة', 'en' => 'Launch Edition Package'],
            ['ar' => 'باقة الذكرى السنوية الخاصة بالشركة', 'en' => 'Anniversary Package'],

            // وضعيات وحراسة إلكترونية وكهربائية
            ['ar' => 'سقف شمسي ذكي لتوليد الكهرباء وتشغيل المكيف', 'en' => 'Solar Roof'],
            ['ar' => 'سقف شحن شمسي متكامل لبطارية السيارة الرئيسية', 'en' => 'Solar Charging Roof'],
            ['ar' => 'وضعية التخييم وتشغيل الكهرباء والحرارة أثناء الوقوف', 'en' => 'Camp Mode'],
            ['ar' => 'وضعية حماية الحيوانات الأليفة مع الحفاظ على التكييف', 'en' => 'Pet Mode'],
            ['ar' => 'وضعية الحراسة والمراقبة بالكاميرات 360 أثناء الوقوف', 'en' => 'Sentry Mode'],
            ['ar' => 'نظام تسجيل رحلات القيادة بكاميرات السيارة أوتوماتيكياً', 'en' => 'Dash Recording'],
            ['ar' => 'وضعية خدمة ركن السيارات وتقييد السرعة والمعلومات', 'en' => 'Valet Mode'],
            ['ar' => 'نظام السياج الجغرافي وتحديد مناطق سير المركبة', 'en' => 'Geo-Fencing'],
            ['ar' => 'محدد السرعة القصوى الإلكتروني الآمن', 'en' => 'Speed Limiter'],
            ['ar' => 'نظام فتح جراج المنزل الرقمي الذكي المدمج', 'en' => 'Digital Garage Opener'],
            ['ar' => 'مخارج تيار كهربائي قوية (110 فولت / 220 فولت)', 'en' => 'Power Outlet (110V / 220V)'],
            ['ar' => 'مخرج مقبس منزلي ثلاثي عادي 220 فولت بالشنطة', 'en' => 'Household Socket'],
            ['ar' => 'تصدير الطاقة الكهربائية للأجهزة والمخيمات الخارجية', 'en' => 'Portable Power Export'],
            ['ar' => 'شحن ثنائي الاتجاه للبطارية وتزويد الشبكة بالطاقة', 'en' => 'Bidirectional Charging'],
            ['ar' => 'تسخين بطارية السيارة مسبقاً قبل الشحن للشحن الفائق', 'en' => 'Battery Preheating'],
            ['ar' => 'تهيئة وإعداد درجة حرارة البطارية للقيادة الرياضية والشحن', 'en' => 'Battery Conditioning'],
        ];

        foreach ($features as $featureData) {
            CarFeature::updateOrCreate(
                ['name->en' => $featureData['en']],
                ['name' => $featureData]
            );
        }
    }
}
